# example of credentials file needed to run

# settings
testing: True # can run in a testing mode which avoids actually triggering ZTF
verbose: True # more print statements
path_data: "data" # path to data directory
observing_run: "O4c" # observing run name

#tokens and passwords
github_token: "github account token used to automatically push event info in the events_summary directory."

# skyportal credentials
fritz_token: "Token for Fritz"
preview_fritz_token: "Preview Token for Fritz"
kowalski_token: "Token for Kowalski"
kowalski_username: "Username for Kowalski"
kowalski_password: "Password for Kowalski"
allocation: 000 # allocation number for ZTF observing program
preview_allocation: 0000 # if running in testing mode, get a fake allocation on preview instance of Fritz

#IPAC credentials (for forced photometry)
zfps_email: "personal user email"
zfps_userpass: "personal user password"
zfps_auth:
  username: "forced photometry service general username"
  password: "forced photometry service general password"

#KAFKA credentials (for LVK alert stream)
client_id: "Kafka client ID"
client_secret: "Kafka client secret"
config_id: "ID for non testing mode, will allow client to track which events have been processed"

# Send email notifications of triggers
sender_email: "set up to come from bbhtrigger@gmail.com"
sender_password: "email account password"
recipient_emails:
  - "list any"
  - "recipient emails"

#slack
slack_webhook: "https://hooks.slack.com/services/hook_for_decam_workspace_BBHBot_channel"
slack_webhook_testing: "https://hooks.slack.com/services/testing_workspace_hook"
